---
- name: Testart traefik
  ansible.builtin.systemd:
    daemon_reload: true
    name: traefik
    state: restarted
  become: true
  tags: traefik

- name: Reload traefik
  ansible.builtin.systemd:
    name: traefik
    state: reloaded
  become: true
  tags: traefik